version: '2'

services:

  fe:
    image: node:7.8.0
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: bash -c "npm install && npm run dev"
    networks:
      - xt-blog
  
  be:
    image: node:7.8.0
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    working_dir: /app
    networks:
      - xt-blog
    command: bash -c "npm install && npm install -g nodemon && nodemon -L ./server/server.js"

  mongodb:
    image: mongo:3.5.5
    volumes: 
      - ./db-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - xt-blog

networks:
  xt-blog:
    driver: bridge